### ISSUE TITLE
Dependency problem

### ISSUE THREAD

**Issue by blkmlk** [dselans/dmidecode#1]
Hi!
Your code will be more helpful if you refuse of dependency of dmidecode binary file. Original dmidecode uses /sys/firmware/dmi/tables/* files to parse hardware information, it will be better if you do it too.

**Comment by lnxbil** [comment]
I agree, yet I have to say that you need Linux 4.x for this, so it will no work on older, e.g. RHEL-based systems below 7.

**Comment by dselans** [comment]
@q1b I wrote this lib as I was exploring Go and wanted to try out process execs and regex. It's true, it should detect platform and read appropriate files (which would allow testing to work better) - but I unfortunately do not have time to do this right now.

Anyone else is welcome to send in a PR and redo this whole thing :-)
